# Generated by Django 5.2.3 on 2025-06-23 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_ticket_approverlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'pcs'), ('kg', 'kg')], default='pcs', max_length=20)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.ticket')),
            ],
        ),
    ]
