# Generated by Django 5.2.3 on 2025-06-25 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_ticketitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
        migrations.AddField(
            model_name='ticket',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approver', to='home.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requestor', to='home.user'),
        ),
        migrations.AlterField(
            model_name='ticketitem',
            name='unit',
            field=models.CharField(choices=[('pcs', 'pcs'), ('kg', 'kg'), ('liter', 'liter'), ('box', 'box'), ('set', 'set')], default='pcs', max_length=20),
        ),
    ]
