# Generated by Django 5.2.3 on 2025-06-25 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_ticket_category_ticket_approver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='approver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='approver', to='home.user'),
            preserve_default=False,
        ),
    ]
