# Generated by Django 5.2.3 on 2025-06-25 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_ticket_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approver', to='home.user'),
        ),
    ]
