# Generated by Django 5.2.3 on 2025-06-25 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_ticket_approver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='expected_delivery',
            new_name='required_by',
        ),
        migrations.RenameField(
            model_name='ticketitem',
            old_name='price',
            new_name='budget',
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(default=2003, on_delete=django.db.models.deletion.RESTRICT, to='home.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='estimated_delivery',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
