# Generated by Django 5.2.3 on 2025-06-25 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_expected_delivery_ticket_required_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='desc',
            new_name='justification',
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='approverlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='comment',
            field=models.TextField(blank=True, default='hi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.company'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.department'),
        ),
    ]
