# Generated by Django 5.2.3 on 2025-06-25 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_desc_ticket_justification_ticket_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='TicketService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DecimalField(decimal_places=1, max_digits=10)),
                ('unit', models.CharField(choices=[('month', 'month'), ('year', 'year'), ('day', 'day'), ('hours', 'hours')], default='month', max_length=20)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.ticket')),
            ],
        ),
    ]
