# Generated by Django 5.2.3 on 2025-06-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_ticket_ticket_id_ticketservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Ordered', 'Ordered'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
