# Generated by Django 5.2.3 on 2025-06-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_ticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketservice',
            old_name='unit',
            new_name='timeunit',
        ),
    ]
