# Generated by Django 5.2.3 on 2025-06-25 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_unit_ticketservice_timeunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketitem',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketservice',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ticket'),
        ),
    ]
