# Generated by Django 5.2.3 on 2025-06-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_ticketitem_ticket_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
