# Generated by Django 5.2.3 on 2025-07-02 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='approverlog',
            name='requestor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='requestor_log', to='home.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approverlog',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='approver_log', to='home.user'),
        ),
    ]
