# Generated by Django 5.2.3 on 2025-07-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_approverlog_requestor_alter_approverlog_approved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approverlog',
            old_name='approved_by',
            new_name='updated_by',
        ),
        migrations.AddField(
            model_name='approverlog',
            name='status',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
