# Generated by Django 5.2.3 on 2025-07-05 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_approved_by_approverlog_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('primary_contact_person', models.CharField(max_length=50)),
                ('primary_contact_person_email', models.EmailField(max_length=254, unique=True)),
                ('primary_contact_person_phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('secondary_contact_person', models.CharField(max_length=50)),
                ('secondary_contact_person_email', models.EmailField(max_length=254, unique=True)),
                ('secondary_contact_person_phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_buffer_days', models.IntegerField()),
                ('NDA_signed', models.BooleanField(default=False)),
                ('onboarding_form_signed', models.BooleanField(default=False)),
                ('PAN', models.FileField(upload_to=None)),
                ('GST_registration_certificate', models.FileField(upload_to=None)),
                ('MSME_certificate', models.FileField(upload_to=None)),
            ],
        ),
    ]
