# Generated by Django 5.2.3 on 2025-07-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.ManyToManyField(to='home.category'),
        ),
    ]
