# Generated by Django 5.2.3 on 2025-07-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_vendor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='firm_type',
            field=models.CharField(choices=[('Sale Proprietorship', 'Sale Proprietorship'), ('Partnership', 'Partnership'), ('Limited Liability Partnership', 'Limited Liability Partnership'), ('Public Limited Company', 'Public Limited Company'), ('Private Limited Company', 'Private Limited Company'), ('One Person Company', 'One Person Company')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
