# Generated by Django 5.2.4 on 2025-07-08 17:43

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_vendor_reference_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='GST_registration_certificate',
            field=models.FileField(upload_to=home.models.vendor_directory_path),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='MSME_certificate',
            field=models.FileField(upload_to=home.models.vendor_directory_path),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='PAN',
            field=models.FileField(upload_to=home.models.vendor_directory_path),
        ),
    ]
