# Generated by Django 5.2.4 on 2025-07-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_vendor_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='rfq_sent',
            field=models.BooleanField(default=False),
        ),
    ]
