# Generated by Django 5.2.4 on 2025-07-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_vendor_rfq_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='rfq_sent',
        ),
        migrations.AddField(
            model_name='ticket',
            name='rfq_sent',
            field=models.BooleanField(default=False),
        ),
    ]
