# Generated by Django 5.2.5 on 2025-09-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_vendor_rfq_sent_ticket_rfq_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='approver',
        ),
    ]
