# Generated by Django 5.2.5 on 2025-09-27 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_ticket_approver'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.ticket')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorItemQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quoted_total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ticket_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ticketitem')),
                ('vendor_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_quotes', to='home.vendorquote')),
            ],
        ),
        migrations.CreateModel(
            name='VendorServiceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quoted_total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ticket_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ticketservice')),
                ('vendor_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_quotes', to='home.vendorquote')),
            ],
        ),
    ]
