# Generated by Django 5.2.5 on 2025-09-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_vendorquote_vendoritemquote_vendorservicequote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendoritemquote',
            old_name='vendor_quote',
            new_name='quote_id',
        ),
        migrations.RenameField(
            model_name='vendorservicequote',
            old_name='vendor_quote',
            new_name='quote_id',
        ),
    ]
